feat: add Avalanche YieldYak fetcher
redstone-finance/redstone-node pull request #108
Opened 2022-07-04 15:09 UTC by cehali

2022-07-05 21:01 UTC, hatskier requested changes
Can you please add another source (as we discussed on oracle standup today), so that we can compare 2 versions:
- With public avalanche RPC endpoint
- With private avalanche RPC endpoint (e.g. using infura endpoint)

2022-07-06 08:05 UTC, cehali commented on src/fetchers/evm-chain/AvalancheYYFetcher.ts
> +    const priceFromApi = await redstone.getPrice("WAVAX");
Added new issue: https://github.com/redstone-finance/redstone-node/issues/114

2022-07-06 08:06 UTC, cehali commented on src/fetchers/evm-chain/AvalancheYYFetcher.ts
> +    connection: string | ethers.utils.ConnectionInfo,
Connection has URL so we can pass only URL, so yes I will delete connection type

2022-07-06 10:24 UTC, cehali commented on src/fetchers/evm-chain/EvmChainFetcher.ts
> +  async fetchData(): Promise<Contract> {
We can do this. Each class that extends `EvmChainFetcher` would need to implement `fetchData` and return `undefined` or something similar. Also, it would need to overwrite `validateResponse` to return `true` if `fetchData` returns something falsy.

2022-07-07 07:38 UTC, cehali commented
Make AvalancheFetcher more generic

2022-07-19 21:31 UTC, hatskier reviewed
Let's do some pair programming :)
I have few ideas for refactoring in the fetcher code

2022-07-19 21:31 UTC, hatskier commented on src/fetchers/index.ts
> +  "avalanche-evm-fetcher": new AvalancheEvmFetcher(
Can we move the configuration for the avalanche evm fetcher (provider, multicall address) to its source code to keep this index.ts file as simple as possible?

2022-07-19 21:31 UTC, hatskier commented on test/fetchers/evm-chain.spec.ts
> +    const result = fetcher.getContractInstance(
Let's not use names like `result` for variables, as it can worsen the code readability ;)

2022-07-21 14:44 UTC, merged