feat: update and adjust streamr integration
redstone-finance/redstone-node pull request #128
Opened 2022-07-14 14:03 UTC by cehali

2022-07-17 18:52 UTC, hatskier requested changes

2022-07-17 18:52 UTC, hatskier commented on tools/streamr/create-stream.ts
> +      auth: { privateKey: privateKey },
Can you please replace `{ privateKey: privateKey }` with `{ privateKey }`?

2022-07-17 18:52 UTC, hatskier commented on tools/streamr/create-stream.ts
> +const privateKey = "";
Can we ask for private key using prompts module?

2022-07-17 18:52 UTC, hatskier commented on tools/streamr/create-stream.ts
> +} from "streamr-client";
Can you add some comments to this file to tell what are the main requirements for creating a new stream (e.g. minimal required Matic balance)?

2022-08-11 11:05 UTC, cehali commented
Updated on monorepo

2022-08-11 11:05 UTC, closed without merging