Hatskier/adding lite evm signature
redstone-finance/redstone-node pull request #17
Opened 2021-08-19 11:36 UTC by hatskier

Adding lite EVM signature to prices and price packages.
Lite EVM signature is used for signing pure data (without types or any unnecessary data). It allows to reduce gas costs for using price data on-chain.

Current signatures:
- signature (main signature, created with the use of Arweave sign function)
- evmSignature (EVM signature, created using `signTypedMessage` method from `eth-sig-util` module)
- liteEvmSignature (Lite EVM signature, created using `personalSign` method from `eth-sig-util` module)

2021-09-01 08:36 UTC, ppedziwiatr requested changes

2021-09-01 08:36 UTC, ppedziwiatr commented on src/types.ts
> +  value: any;
what types are allowed here? maybe it would be good to specify them here explicitly?

Just a general comment - I would try to avoid using `any` in the whole codebase - we're using "Type"Script here,
so let's try to specify the types....

2021-09-01 08:36 UTC, ppedziwiatr commented on src/signers/EvmPriceSigner.ts
> +  getDataToSign(priceData: SerializedPriceData): any {
can we please move to strictly defined types (instead of "any") - at least for the public API?

2021-09-01 08:36 UTC, ppedziwiatr commented on test/EvmPriceSigner.spec.ts
> +  it("should fail verifying wrong lite signature", () => {
I like the tests 👍

2021-09-01 08:36 UTC, ppedziwiatr commented on test/EvmPriceSigner.spec.ts
> +      "timestamp": Date.now(),
I think the general rule in the unit tests is to mock the "current time" to a some concrete value - as using "Date.now()" may cause that some tests will become non-deterministic.
Jest has even a built-in feature for this:
```
jest
  .useFakeTimers('modern')
  .setSystemTime(new Date('2021-09-01').getTime());
```

2021-09-02 22:31 UTC, hatskier commented on src/types.ts
> +  value: any;
As we decided, all types should be allowed here

2021-09-02 22:32 UTC, hatskier commented on src/signers/EvmPriceSigner.ts
> +  getDataToSign(priceData: SerializedPriceData): any {
Sure :)

2021-09-02 22:32 UTC, hatskier commented on test/EvmPriceSigner.spec.ts
> +      "timestamp": Date.now(),
Added

2021-09-03 11:08 UTC, jakub-wojciechowski commented on src/types.ts
> +  value: any;
We stil have uint256 in:
const PriceData = [
  { name: "symbols", type: "bytes32[]" },
  { name: "values", type: "uint256[]" },
  { name: "timestamp", type: "uint256" },

We also use it on the contracts site. 
It's not an issue now but let's be aware of that before adding different types than numbers (we're not ready for that yet)

2021-09-03 11:13 UTC, jakub-wojciechowski approved these changes

2021-09-06 07:32 UTC, merged