Hatskier/adding pangoling fetcher
redstone-finance/redstone-node pull request #18
Opened 2021-08-20 09:11 UTC by hatskier

Added Pangolin fetcher. Pangolin is a DEX (like Uniswap or Sushiswap) built on Avalanche and for Avalanche tokens.
The implementation of Pangolin fetcher is based on DexFetcher, which is also used in Uniswap and Sushiswpa fetcher, because all these fetchers use The Graph protocol to fetch pricing data.

2021-09-01 08:59 UTC, ppedziwiatr requested changes

2021-09-01 08:59 UTC, ppedziwiatr commented on manifests/okex5.json
> -    "QUN": {},
btw., what is the difference between okex5, okex3, okex? Different API versions? maybe we should use only the latest one?

2021-09-01 08:59 UTC, ppedziwiatr commented on src/fetchers/pangolin/all-pangolin-fetchers.ts
> +// TODO: add types
yes, please :-)

2021-09-01 08:59 UTC, ppedziwiatr commented on test/median-aggregator.spec.ts
> +    expect(getMedianValue([3, 7, 2, 6, 5, 4, 9], "")).toEqual(5);
so the the "symbol" parameter is not required? Maybe it could have a default value?

2021-09-01 08:59 UTC, ppedziwiatr commented on src/aggregators/median-aggregator.ts
> +      `Cannot get median value of an empty array for symbol: ${symbol}`);
hmm, so the only point of adding the symbol here is to log it in an error? Maybe it should be then the caller responsibility (who already knows the symbol) to verify if the arr is empty?

2021-09-02 22:30 UTC, hatskier commented on test/median-aggregator.spec.ts
> +    expect(getMedianValue([3, 7, 2, 6, 5, 4, 9], "")).toEqual(5);
Removed param symbol

2021-09-02 22:30 UTC, hatskier commented on src/aggregators/median-aggregator.ts
> +      `Cannot get median value of an empty array for symbol: ${symbol}`);
Good idea!

2021-09-02 22:30 UTC, hatskier commented on src/fetchers/pangolin/all-pangolin-fetchers.ts
> +// TODO: add types
Added :)

2021-09-02 22:31 UTC, hatskier commented on manifests/okex5.json
> -    "QUN": {},
Removed okex3 and okex. These are older versions of okex

2021-09-03 11:22 UTC, jakub-wojciechowski requested changes

2021-09-03 11:22 UTC, jakub-wojciechowski commented on src/aggregators/median-aggregator.ts
> +    if (stableValues.length === 0) {
What if we've got one reliable source that says price is 100, and one faulty which says the price is 0. Will we calculate median (50) and reject all the values?

2021-09-03 11:22 UTC, jakub-wojciechowski commented on src/fetchers/pangolin/PangolinFetcher.ts
> +      if (reserveUSD > MIN_RESERVE_USD) {
It's not urgent but the logic here is almost the same as in DexFetcher - we may just record a task to refactor it in the future.

2021-09-03 12:09 UTC, hatskier commented on src/aggregators/median-aggregator.ts
> +    if (stableValues.length === 0) {
0 value will be filtered out firstly. Then only 100 will be used to calculate median (everything will be OK in this case). But if some faulty source says it's 0.1, while reliable source says it's 100 - we'll reject both prices, because we would need some additional logic to decide, which source is more reliable in this case.

2021-09-06 07:25 UTC, hatskier commented on src/fetchers/pangolin/PangolinFetcher.ts
> +      if (reserveUSD > MIN_RESERVE_USD) {
Done :) https://app.clickup.com/t/11ea49u

2021-09-06 07:25 UTC, merged