docs review
redstone-finance/redstone-node pull request #22
Opened 2021-09-27 08:25 UTC by ppedziwiatr

2021-09-27 09:57 UTC, jakub-wojciechowski requested changes

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +- To reduce costs current providers cover only a small subset of tokens (Chainlink: 25 - PPE - this information is out of date - https://data.chain.link/?_ga=2.221957087.616302317.1632727519-14521256
Let's put 79 cryptocurrencies.

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +- To reduce costs current providers cover only a small subset of tokens (Chainlink: 25 - PPE - this information is out of date - https://data.chain.link/?_ga=2.221957087.616302317.1632727519-14521256
Chainlink recently added an optimisation that the price could be delayed for a longer period in case the deviation is small. The best case scenario is 3600s, so let's put at least 10 minutes)

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +- **Dispute resolution protocol** - a set of Arweave (are we sure we want to implement this on Arweave?)  contracts allowing to challenge any existing pricing feed, and managing the dispute process e
Yes, that's our current intention.

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +  "AR": 45.083730599999996 (why is this price stored in a tag?)
@hatskier Could you please comment on that (we wanted the AR price to be most available, right?)

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +##### Local run (either add warning regarding running on Windows or remove the part?)
Let's add warning recommendation to run on Unix @hatskier

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +Providers registry is an Arweave smart contract that manages provider's token stake, holds the manifest (SLA of pricing data) and allows checking historical performance (showing any data inconsistenc
The contract description should be updated, could you help with that @ppedziwiatr ?

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +Decentralised data feeds have many advantages over centralised competitors. They are more secure (why?), lacking a central point of failure and more censorship-resilient because of diversified govern
it's more secure because it lacks a central point of failure

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +New generations of blockchains like Arweave could finally make the implementation of Schelling-point based algorithms economically feasible due to the cheaper storage and low contracts execution cost
Let's put a link there: https://github.com/alice-si/TcrSimulation.jl

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +Jurors vote by staking their tokens either to support or reject the dispute. The maximum amount of tokens that could be staked is limited by their an (this sentence makes no sense..) additional param
Yes, there is a typo. Let's make it @hatskier :

Jurors vote by staking their tokens either to support or reject the dispute. The maximum amount of tokens that could be staked is limited by an additional parameter called "voting capacity" (see the challenges section for more details).

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +Jurors vote by staking their tokens either to support or reject the dispute. The maximum amount of tokens that could be staked is limited by their an (this sentence makes no sense..) additional param
The section is called Challenges and it's below :) 
(I'd avoid internal links if we want to export the doc to pdf)

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +After the verdict is final the winning party receives a reward which is taken either from a challenger fee or provider deposit. Part of the reward is distributed to the judges (who are the judges? wh
can they be punished for a "wrong" verdict? - this is answered in the next sentence.
Judges have been introduced a few paragraphs above.
If you think it'd be more readable feed free to add a section listing all the actors in points (jurors, challenger, challengee) @ppedziwiatr

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +| min challenge fee | 100 RDST (why 100 and not 500 or 1000? shouldn't it depend on the market value of the token?) | A minimum amount of tokens that need to be staked by the watcher (challenger) |
It's a good point let's put at least $100 worth of Redstone Tokens @hatskier .

2021-09-27 09:57 UTC, jakub-wojciechowski commented on docs/COMPILED_ORACLE_DOCS.md
> +`redstone-flash-storage` implements an alternative design of providing data to smart contracts. Instead of constantly persisting data on EVM storage, the information is brought on-chain only when nee
This is a good resource: https://docs.openzeppelin.com/learn/sending-gasless-transactions

(this somewhat suggests that data is transferred from Arweave, which ofc. is not the case...)

2021-09-27 10:05 UTC, hatskier commented on docs/COMPILED_ORACLE_DOCS.md
> +  "AR": 45.083730599999996 (why is this price stored in a tag?)
Yes, we wanted to make getting AR price from Arweave as easy as possible

2021-09-27 18:38 UTC, hatskier commented on docs/COMPILED_ORACLE_DOCS.md
> +- To reduce costs current providers cover only a small subset of tokens (Chainlink: 25 - PPE - this information is out of date - https://data.chain.link/?_ga=2.221957087.616302317.1632727519-14521256
fixed

2021-09-27 18:41 UTC, hatskier commented on docs/COMPILED_ORACLE_DOCS.md
> +##### Local run (either add warning regarding running on Windows or remove the part?)
added

2021-09-27 18:44 UTC, hatskier commented on docs/COMPILED_ORACLE_DOCS.md
> +New generations of blockchains like Arweave could finally make the implementation of Schelling-point based algorithms economically feasible due to the cheaper storage and low contracts execution cost
done

2021-09-27 18:48 UTC, hatskier commented on docs/COMPILED_ORACLE_DOCS.md
> +Jurors vote by staking their tokens either to support or reject the dispute. The maximum amount of tokens that could be staked is limited by their an (this sentence makes no sense..) additional param
fixe the typo

2021-09-27 18:50 UTC, hatskier commented on docs/COMPILED_ORACLE_DOCS.md
> +| min challenge fee | 100 RDST (why 100 and not 500 or 1000? shouldn't it depend on the market value of the token?) | A minimum amount of tokens that need to be staked by the watcher (challenger) |
done

2021-09-27 18:55 UTC, hatskier commented on docs/COMPILED_ORACLE_DOCS.md
> +`redstone-flash-storage` implements an alternative design of providing data to smart contracts. Instead of constantly persisting data on EVM storage, the information is brought on-chain only when nee
added a link

2021-11-02 17:50 UTC, hatskier commented
Closing the Pull Request. We've done with the docs at this moment

2021-11-02 17:50 UTC, closed without merging