Evm signature support
redstone-finance/redstone-node pull request #4
Opened 2021-06-12 13:43 UTC by hatskier

2021-06-14 12:34 UTC, jakub-wojciechowski requested changes

2021-06-14 12:34 UTC, jakub-wojciechowski commented on src/NodeRunner.ts
> +    this.evmSigner = new EvmPriceSigner(this.version, 1);
Could we please:
1) Take only the major.minor version and skip patch - to avoid contracts upgrade on every change
2) Take chain id from manifest?

2021-06-14 12:34 UTC, jakub-wojciechowski commented on src/NodeRunner.ts
> +    await this.savePricePackage(signedPrices);
Hmm, could we change the same to sth like prepareAndBroadcastSignedPackage or just bradcastEvmPackage (the current one focus on saving, but in fact it broadcasts)

2021-06-14 12:34 UTC, jakub-wojciechowski commented on src/NodeRunner.ts
> +    logger.info("Saving price package");
What do you think about wrapping only signing in try-catch. We could then 
1) have separate time tracking for signing
2) catch separately errors for signing (broadcasting has got an own try-catch block)

2021-06-14 12:34 UTC, jakub-wojciechowski commented on src/utils/EvmPriceSigner.ts
> +  verifySignature(signedPriceData: SignedPricePackage): boolean {
We can also rename signedPriceData ->  signedPricePackage

2021-06-14 12:34 UTC, jakub-wojciechowski commented on test/EvmPriceSigner.spec.ts
> +  it("should fail verifyung wrong signature", () => {
typo in verifyung

2021-06-14 12:34 UTC, jakub-wojciechowski commented on test/EvmPriceSigner.spec.ts
> +});
Could we add a test to check signing and verification from eth priv key that doesn't match signer address?

2021-06-15 07:40 UTC, hatskier commented on src/NodeRunner.ts
> +    this.evmSigner = new EvmPriceSigner(this.version, 1);
1. It already works this way https://github.com/redstone-finance/redstone-node/blob/main/src/NodeRunner.ts#L196
2. Sure :)

2021-06-15 08:24 UTC, hatskier commented on src/NodeRunner.ts
> +    logger.info("Saving price package");
I would not wrap signing in try-catch block, because if package signing doesn't work we want to throw an exception and stop the package broadcasting process. If we add signing in try-catch we will need to handle it manually and the code would be less readable IMO. We still will be able to analyze package signing timings, because we have a timing for the whole process and a separate timing for broadcasting

2021-06-15 08:28 UTC, hatskier commented on test/EvmPriceSigner.spec.ts
> +});
Added

2021-06-15 08:28 UTC, hatskier commented on test/EvmPriceSigner.spec.ts
> +  it("should fail verifyung wrong signature", () => {
Fixed

2021-06-15 08:28 UTC, hatskier commented on src/utils/EvmPriceSigner.ts
> +  verifySignature(signedPriceData: SignedPricePackage): boolean {
Done

2021-06-15 08:28 UTC, hatskier commented on src/NodeRunner.ts
> +    await this.savePricePackage(signedPrices);
Done

2021-06-15 13:35 UTC, merged