Move redstone oracle registry to node repository
redstone-finance/redstone-node pull request #51
Opened 2022-04-11 12:49 UTC by cehali

2022-04-14 11:59 UTC, hatskier requested changes
Great work!

2022-04-14 11:59 UTC, hatskier commented on src/contracts/redstone-oracle-registry/handleEvolve.ts
> +import {
Please fix formatting (identations) in this file

2022-04-14 11:59 UTC, hatskier commented on src/contracts/redstone-oracle-registry/initial-state.json
> +{
Please rename data feed ids in this file to the following values:
- `provider_qZfxiw8Rl3ywD9e4F-nxLOCzZqU1MibNcep4DWvTgkQ`: `redstone-main-demo`
- `provider_gd0Vwzb2o6B5n68Sik3Lk0vv8sL2Ee1JcWn7DAx8_VY`: `redstone-rapid-demo`
- `provider_LxY82d0TlGNqDf9jWSb6LlAVszL2OubAFG9QV3RiWC4`: `redstone-stocks-demo`
- `provider_qZfxiw8Rl3ywD9e4F-nxLOCzZqU1MibNcep4DWvTgkQ`: `redstone-main-demo`
- `provider_vNgkmusqWpE_4E8Kn1ar_GCrTBmWEH9BNcV08krPa8M`: `redstone-avalanche-demo`
- `provider_kKqwbcrdrmPoZLBqjM5HGmDOMEicPli0P_Z-G_Ib09w`: `redstone-avalanche-prod`

Remove the following data feeds:
- `provider_khZSCTL02bIQNfx-o_pbiDjuiFBL-oyvcbAIM2DAB50`
- `provider_fg97Q4mOS0LuiEE9TZqauOSPbgVyUo9xQtVmWhpPI9Q`
- `provider_SjR1m8EBcCoON0N11LEQGzqjmaJissWtoEZuuyTTRpQ`
- `provider_vrEspHV3JLX_3BPL3Jm7ofneAdMqOJiwZvv0a2lL-rg`

The idea is that redstone-avalanche-node-1 and redstone-avalanche-node-2 should be linked to the same data feed (redstone-avalanche-demo). And redstone-avalanche-prod-node-[1, 2 and 3] should be linked to redstone-avalanche-prod data feed.

2022-04-14 11:59 UTC, hatskier commented on src/contracts/redstone-oracle-registry/redstone-oracle-registry.contract.ts
> +type ContractResult =
Why have you decided to put this type here (not in types.ts file)?

2022-04-14 11:59 UTC, hatskier commented on src/contracts/redstone-oracle-registry/redstone-oracle-registry.contract.ts
> +      return handleEvolve(state, action);
What do you think about naming this function (and the file) `evolve` instead of `handleEvolve` (for consistency)?

2022-04-14 11:59 UTC, hatskier commented on src/contracts/redstone-oracle-registry/data-feeds/read/getDataFeedDetailsById.ts
> +export const getDataFeedDetailsById = (
Just an idea: maybe we can refactor read functions in data-feeds and nodes (getDataFeedDetails, listDataFeeds, getNodeDetails, listNodes) by creating a common utils module (since their logic seems very similar)

The only shortcoming of this refactoring would be that it will be more difficult to add custom logic to these functions later.

What do you think?

2022-04-14 11:59 UTC, hatskier commented on src/contracts/redstone-oracle-registry/data-feeds/read/getDataFeedDetailsById.ts
> +  return { result: { ...dataFeedDetails, id: id } };
Can we replace `id: id` with `id`?

2022-04-15 09:51 UTC, cehali commented on package.json
> +    "build:contracts": "rm -rf dist && node ./tools/contracts/build.js && npm run cp",
Yes, I will change to yarn.
Problem with `cp` instead of `copyfiles` is that I am not sure how to mimic the same behaviour. We need to find all json files and copy them to dist folder into folders with corresponding contracts names because each json file probably will be initial-state.json. I am not saying that it is not possible but could be complicated and I just used the solution from academy. Example how it look now below:

![image](https://user-images.githubusercontent.com/35804520/163556610-7b25ba38-ed0e-4a82-9727-af9682426c93.png)

2022-04-15 10:34 UTC, cehali commented on tsconfig.json
> +    "target": "es6",
Some things in contracts are not supported in es5, we would need to use babel or other transpiler 
![image](https://user-images.githubusercontent.com/35804520/163560997-3f09f008-e87b-4106-a56e-210db8fcd9df.png)

2022-04-15 11:03 UTC, cehali commented on src/contracts/redstone-oracle-registry/redstone-oracle-registry.contract.ts
> +type ContractResult =
No reason, I probably forgot to move in types

2022-04-15 12:51 UTC, cehali commented on src/contracts/redstone-oracle-registry/data-feeds/read/getDataFeedDetailsById.ts
> +export const getDataFeedDetailsById = (
I provided a proposition for this refactoring. I added two files: `listWithPagination` and `getOracleDetails`. I am wondering if unified error messages are right, maybe we should distinguish them based on oracle type in order to make them more informative.

2022-04-20 07:32 UTC, merged