feat: move configuration to env variables
redstone-finance/redstone-node pull request #95
Opened 2022-06-07 10:40 UTC by cehali

2022-06-09 20:14 UTC, hatskier requested changes

2022-06-09 20:14 UTC, hatskier commented on docs/PREPARE_ENV_VARIABLES.md
> +| OMIT_SOURCES_ARWEAVE_TX                      |                       optional                        | if set to true, single source will not be attached to bundlr transaction
`if set to true, single source will not be attached to bundlr transaction ` -> `if set to true, values from different sources will not be attached to the data backup on Arweave`

2022-06-09 20:14 UTC, hatskier commented on docs/PREPARE_ENV_VARIABLES.md
> +| ENABLE_STREAMR_BROADCASTER                   |                       required                        | if set to true, single prices and prices packages will be sent to Streamr
Can't it be optional (with the default `false` value)?

2022-06-09 20:14 UTC, hatskier commented on docs/PREPARE_ENV_VARIABLES.md
> +| HTTP_BROADCASTER_URLS                        |                       optional                        | array of urls for broadcasters to which prices should be sent
I would set it as required

2022-06-09 20:14 UTC, hatskier commented on docs/PREPARE_ENV_VARIABLES.md
> +| Param                                        |                      Optionality                      | Description
Can we add a column with default values for the optional params?

2022-06-09 20:14 UTC, hatskier commented on package.json
> +    "start:sample": "ENABLE_JSON_LOGS=true yarn start:dev > tmp.out",
I think we can remove `ENABLE_JSON_LOGS=true` here now :)

2022-06-09 20:14 UTC, hatskier commented on src/config/getArweaveWallet.ts
> +  const arweaveKeysFile = process.env.ARWEAVE_KEYS_FILE_PATH;
Can we create a single module (e.g. `config.ts`), which will be responsible for collecting all values from env variables and validating them? Then any other module will be able to ask the config.ts module about the requested value

2022-06-09 20:14 UTC, hatskier commented on src/config/getConfigFromEnv.ts
> +export function getFromEnv(envName: string, required: false): string | undefined
Please rename this file according to other filenames (e.g. get-config-from-env.ts)

2022-06-09 20:14 UTC, hatskier commented on src/config/getArweaveWallet.ts
> +import { readJSON } from "../utils/objects";
Please rename this file to `get-arweave-wallet.ts`

2022-06-09 20:14 UTC, hatskier commented on src/config/getConfigFromEnv.ts
> +export function getFromEnv(envName: string, required: false): string | undefined
Shouldn't we add `import "dotenv/config";` on top of this file?
More info here: https://github.com/motdotla/dotenv#how-do-i-use-dotenv-with-import

2022-06-09 20:14 UTC, hatskier commented on .env.example
> +MANIFEST_FILE_PATH="./sample-jwk.json"
Please replace this path to "./manifests/dev.json"

2022-06-09 20:14 UTC, hatskier commented on .env.example
> +ARWEAVE_KEYS_FILE_PATH=./sample-jwk.json
Can you remove `ARWEAVE_KEYS_JWK={"kty...` since you specify the `ARWEAVE_KEYS_FILE_PATH` here?

2022-06-10 11:00 UTC, skromez commented
@cehali also wanted to mention, that in this pull request #93 I've added a variable in a config called **twelveDataRapidApiKey** and it also needs to be moved to the env variables and be replaced in twelve-data-fetcher

2022-06-13 08:24 UTC, cehali commented on .env.example
> +Notes:
This one is only an example, it shouldn't be used as an env file. Someone should only copy it content but copy it with precautious 😄 I moved notes to the top of the file.

2022-06-13 08:27 UTC, cehali commented on .env.example
> +ARWEAVE_KEYS_FILE_PATH=./sample-jwk.json
I think we need to discuss it in person, whole .env.example file. Should it show all possibilities or be a minimum working example.

2022-06-13 08:29 UTC, cehali commented on docs/PREPARE_ENV_VARIABLES.md
> +| ENABLE_STREAMR_BROADCASTER                   |                       required                        | if set to true, single prices and prices packages will be sent to Streamr
Ok, this changes a lot of things. When I was deciding if values should be optional or required I went through a type of config object. But now I think that the config object should have all parameters, no optionals at all, and parameters not passed in env file should have some default value

2022-06-13 08:33 UTC, cehali commented on src/config/getConfigFromEnv.ts
> +export function getFromEnv(envName: string, required: false): string | undefined
We haven't used `dotenv` at all but I agree that we should add it

2022-06-15 12:28 UTC, cehali commented
@hatskier I remodeled config file so please treat this PR as completely new one 😄

2022-06-23 00:52 UTC, hatskier requested changes
Let's discuss with me and Jakub which env config variables
- can be moved to manifest
- can be removed
- can be optional (with default value), and which should be required

I've also added few comments regarding the current implementation

2022-06-23 00:52 UTC, hatskier commented on .jest/setEnvVars.js
> +process.env.ARWEAVE_KEYS_JWK = JSON.stringify({ e: "e", kty: "kty", n: "n" });
Just to clarify: will it set env vars only for the time of testing?

2022-06-23 00:52 UTC, hatskier commented on docs/ENVIRONMENTS.md
> +ENV HTTP_BROADCASTER_URLS=["https://api.redstone.finance","https://vwx3eni8c7.eu-west-1.awsapprunner.com","https://container-service-1.dv9sai71f4rsq.eu-central-1.cs.amazonlightsail.com"]
Do you think we can also move broadcasting config (incl. streamr broadcasting and http broadcasting) to the manifest within this Pull Request?

2022-06-23 00:52 UTC, hatskier commented on index.ts
> +      "USAGE: yarn start:prod");
Let's not print `USAGE: ...` here. Let's replace this message to smth like "Please find details about the correct node running at https:///some-address-to-docs-on-github/...

2022-06-23 00:52 UTC, hatskier commented on src/config/config.ts
> +    console.log({ dupa: process.env[envName] })
Lol 😂

2022-06-23 00:52 UTC, hatskier commented on src/config/config.ts
> +    console.log({ dupa: process.env[envName] })
Let's try to keep our secret debugging sauce privately 😉

2022-06-23 00:52 UTC, hatskier commented on src/config/config.ts
> +function getFromEnv(envName: string, defaultValue?: string | number): string
- Do we really need the 3 lines before the actual implementation?

2022-06-23 00:52 UTC, hatskier commented on src/config/config.ts
> +function getFromEnv(envName: string, defaultValue?: string | number | boolean | string[]) {
Why do you use `function getFromEnv(...` notation instead of `const getFromEnv = (...)` as you usually do in other places?

2022-06-23 00:52 UTC, hatskier commented on src/config/config.ts
> +function getFromEnv(envName: string, defaultValue?: string | number | boolean | string[]) {
Can't the defaultValue have the `any` type?

2022-06-23 00:52 UTC, hatskier commented on src/config/config.ts
> +  return valueFromEnv;
Shouldn't we raise some error in this case, like "Unsupported boolean value: ${valueFromEnv}. Only true and false string values are supported for the boolean type`?

2022-06-23 00:52 UTC, hatskier commented on src/config/config.ts
> +export const getArweaveWallet = () => {
Can we add a return type to this function?

2022-06-23 00:52 UTC, hatskier commented on src/config/config.ts
> +  enableJsonLogs: getFromEnv("ENABLE_JSON_LOGS", true),
Can you move default values to constants (e.g.  `const DEFAULT_ENABLE_JSON_LOGS = true; const DEFAULT_PERFORMANCE_TRACKING_LABEL_PREFIX = "public"`)?
Or do you think it can make the code less readable?

2022-06-23 00:52 UTC, hatskier commented on src/config/config.ts
> +  manifestRefreshInterval: Number(getFromEnv("MANIFEST_REFRESH_INTERVAL", 120000)),
Let's create a special `getNumberFromEnv` function to correctly handle `NaN`s

2022-06-23 00:52 UTC, hatskier commented on src/config/config.ts
> +  disableSinglePricesBroadcastingInStreamr: getFromEnv(
This one can also be saved in manifest

2022-06-23 00:52 UTC, hatskier commented on src/utils/error-reporter.ts
> +import { config } from "../config/config";
Do we really need a separate folder for the config file?

2022-06-23 06:28 UTC, cehali commented on .jest/setEnvVars.js
> +process.env.ARWEAVE_KEYS_JWK = JSON.stringify({ e: "e", kty: "kty", n: "n" });
Yes, it is rather standard operation to mock env variables in test: https://dev.to/darkmavis1980/how-to-mock-environmental-variables-with-jest-2j3c

2022-06-23 06:30 UTC, cehali commented on docs/ENVIRONMENTS.md
> +ENV HTTP_BROADCASTER_URLS=["https://api.redstone.finance","https://vwx3eni8c7.eu-west-1.awsapprunner.com","https://container-service-1.dv9sai71f4rsq.eu-central-1.cs.amazonlightsail.com"]
We have to discuss what responsibility should be on a manifest and what responsibility should be on env variables.

2022-06-23 06:33 UTC, cehali commented on src/config/config.ts
> +function getFromEnv(envName: string, defaultValue?: string | number): string
I though that overloading functions is not supported in arrow functions but it seems that it is now: https://stackoverflow.com/questions/39187614/typescript-overload-arrow-functions

2022-06-23 06:34 UTC, cehali commented on src/config/config.ts
> +function getFromEnv(envName: string, defaultValue?: string | number | boolean | string[]) {
I though that overloading functions is not supported in arrow functions but it seems that it is now: https://stackoverflow.com/questions/39187614/typescript-overload-arrow-functions

2022-06-23 06:37 UTC, cehali commented on src/config/config.ts
> +function getFromEnv(envName: string, defaultValue?: string | number | boolean | string[]) {
I prefer function overloading: https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads. `any` is so much taking easy way 😄

2022-06-23 07:45 UTC, cehali commented on src/config/config.ts
> +  manifestRefreshInterval: Number(getFromEnv("MANIFEST_REFRESH_INTERVAL", 120000)),
But you will not have `NaN`s here. Either it will be a number as string value or a default number value.

2022-06-23 07:46 UTC, cehali commented on src/utils/error-reporter.ts
> +import { config } from "../config/config";
Folder `config` was already there. I created a separate file config.

2022-06-23 08:53 UTC, cehali commented on src/config/config.ts
> +  return valueFromEnv;
Sounds good 😄

2022-06-23 08:58 UTC, cehali commented on src/config/config.ts
> +  enableJsonLogs: getFromEnv("ENABLE_JSON_LOGS", true),
I like it

2022-06-23 09:32 UTC, cehali commented on src/config/config.ts
> +  return valueFromEnv;
Sorry, we cannot. It works a little bit differently. If value from env is boolean string, it is parsed to boolean. I will change the name of the function because it is a little bit misleading.

2022-06-23 09:38 UTC, cehali commented on src/config/config.ts
> +function getFromEnv(envName: string, defaultValue?: string | number | boolean | string[]) {
Sorry once again, it seems that it doesn't work as proper as it should. I came across the same problem: `Also, to preface any questions regarding that, yeah I've declared the parameter as any in the implementation. This is neccessary at the current state to allow compilation, and yeah, you will loose type-safety inside the function, as @ford04 pointed out. It seems typescript still cant process flagged unions correctly when it comes to functions and their returns. Alternatively you can have stricter parameters but then you will have to cast the return to any.`

2022-06-23 10:38 UTC, hatskier commented on src/config/config.ts
> +function getFromEnv(envName: string, defaultValue?: string | number): string
But do we really need the overloading here?

2022-06-23 10:40 UTC, cehali commented on src/config/config.ts
> +function getFromEnv(envName: string, defaultValue?: string | number): string
I think yes. Then we know what type of variable would be depending on `defaultValue`

2022-06-29 16:00 UTC, cehali commented on src/utils/error-reporter.ts
> +import { config } from "../config/config";
I moved `config` file to main `src` folder

2022-07-06 14:10 UTC, hatskier approved these changes
Please check few minor cosmetic comments and merge this PR :)

2022-07-06 14:31 UTC, cehali commented on src/config.ts
> +const getFromEnv = <T>(envName: string, defaultValue?: any): T => {
![image](https://user-images.githubusercontent.com/35804520/177574917-c83d81a7-a046-4d9f-b6ad-07996b7929b1.png)

2022-07-07 09:11 UTC, cehali commented on src/config.ts
> +    null
Refactored during our pair programming session

2022-07-07 09:23 UTC, cehali commented on docs/DOCKER.md
> +Dockerfiles are used to build docker images, which are usually executed in Production environment. To configure production environment `ENV` instruction should be added to a Dockerfile.
Yes, this is an obsolete instruction from the previous version

2022-07-07 09:28 UTC, merged