feat: add coinbase to ccxt fetcher
redstone-finance/redstone-node pull request #96
Opened 2022-06-07 15:43 UTC by cehali

2022-06-09 19:36 UTC, hatskier requested changes
Why do you update a lot of other manifests (not related to coinbase) here? If this PR also handles the data cleaning, can you please rename it? :)

Can you also update the list of sources metadata according to [this document](https://github.com/redstone-finance/redstone-node/blob/main/docs/ADD_NEW_SOURCE.md)?

2022-06-09 19:36 UTC, hatskier commented on src/fetchers/ccxt/CcxtFetcher.ts
> +        ? ticker.info
Hmm, looks a bit hacky. Can you please describe why the Coinbase fetcher needs another logic than other ccxt fetchers?

2022-06-13 11:56 UTC, cehali commented
I run scripts for ccxt and this is result 😄 Yes, I will remove all other changes and leave ones regarding coinbase

2022-06-13 12:13 UTC, cehali commented on src/fetchers/ccxt/CcxtFetcher.ts
> +        ? ticker.info
Here example: 
<img width="314" alt="image" src="https://user-images.githubusercontent.com/35804520/173351003-400af3e5-21c5-4588-baf3-a5b1a40cbb26.png">

2022-06-15 06:57 UTC, cehali commented
Removed plain coinbase from ccxt and deleted remaining of coinbase fetcher

2022-06-22 23:56 UTC, merged